---
- hosts: localhost
  connection: localhost
  become: true

  tasks:
    - name: install packages
      package:
        name:
          - htop
          - tmux
          - vim
          - python3-psutil
    
    - name: copy wallpaper file
      copy:
        src: files/wallpaper.jpg
        dest: /usr/share/backgrounds/ansible-wallpaper.jpg
        owner: root
        group: root
    
    - name: set wallpaper
      become_user: eshearer
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"
    
    - name: set wallpaper postion
      become_user: eshearer
      dconf:
        key: "/org/gnome/desktop/background/picture-options"
        value: "'zoom'"

    - name: add ansible user
      user:
        name: ansible
        system: yes

    - name: set up sudo for ansible user
      copy:
        src: files/sudoer_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440

    - name: add ansible-pull cron job
      cron:
        name: ansible auto-provision
        user: ansible
        minute: "*/15"
        job: /usr/bin/ansible-pull -o -U https://github.com/evan684/ansible_desktop.git